// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
  ASSET: Fetcher;
  DB: D1Database;
  VAPID_PUBLIC_KEY: string;
  VAPID_SUBJECT: string;
  /** Secret: `wrangler secret put VAPID_PRIVATE_KEY` (locally in .dev.vars). */
  VAPID_PRIVATE_KEY: string;
}
